
# Bilingual support: English / German

class LanguageSystem:
    """Bilingual support system for English and German."""

    TRANSLATIONS = {
        'en': {
            'dashboard_title': "🔧 BRUSS Predictive Maintenance Dashboard",
            'dashboard_subtitle': "Real-time monitoring, predictive analytics, and email alerts",
            'language_label': "🌐 Language / Sprache",
            'total_machines': "Total Machines",
            'critical_alerts': "Critical Alerts",
            'email_status': "Email Status",
            'email_controls': "📧 Email Alert Controls",
            'test_email_recipient': "Test Email Recipient:",
            'send_test_email': "Send Test Email",
            'quick_actions': "Quick Actions:",
            'send_daily_report': "📋 Send Daily Report",
            'send_critical_alerts': "⚠️ Send Critical Alerts",
            'recent_alerts': "🚨 Recent Alerts",
            'no_recent_alerts': "No recent alerts",
            'select_machines': "🏭 Select Machines",
            'select_time_range': "📈 Select Time Range",
            'overview': "📊 Overview",
            'sensor_analytics': "📈 Sensor Analytics",
            'predictive_insights': "🔍 Predictive Insights",
            'maintenance_schedule': "📋 Maintenance Schedule",
            'email_history': "📧 Email History",
            'visual_diagnostics': "🔬 Visual Diagnostics",
            'shift_report': "📄 Shift Handover Report",
            'health_distribution': "Health Score Distribution",
            'risk_distribution': "Risk Level Distribution",
            'temperature_trends': "Temperature Trends",
            'power_vibration': "Power & Vibration",
            'tool_wear': "Tool Wear",
            'vibration_analysis': "3D Vibration Analysis",
            'failure_probability': "Failure Probability Over Time",
            'rul_estimation': "Top 20 Machines by Estimated RUL",
            'feature_importance': "Feature Importance for Failure Prediction",
            'maintenance_recommendations': "🛠️ Maintenance Recommendations",
            'machine_id': "Machine ID",
            'health_score': "Health Score",
            'risk_level': "Risk Level",
            'estimated_rul': "Estimated RUL (hours)",
            'maintenance_urgency': "Maintenance Urgency",
            'recommended_action': "Recommended Action",
            'email_alert_history': "📧 Email Alert History",
            'email_stats': "📧 Email Statistics (Last 24h)",
            'total_sent': "Total Sent:",
            'critical': "Critical",
            'last_alert': "Last Alert:",
            'timestamp': "Timestamp",
            'severity': "Severity",
            'subject': "Subject",
            'recipients': "Recipients",
            'select_machine_type': "Select Machine Type:",
            'select_machine_id': "Select Machine ID:",
            'cnc_machine': "CNC Machine",
            'rep_machine': "Robotic End-Effector",
            'part_status': "Part Status",
            'normal': "Normal",
            'warning': "Warning",
            'machine_schematic': "Machine Schematic",
            'part_alerts': "Part Alerts",
            'machine_details': "Machine Details",
            'current_health': "Current Health Score:",
            'failure_prob': "Failure Probability:",
            'machine_type': "Machine Type:",
            'last_update': "Last Update:",
            'no_data_for_machine': "No data available for selected machine",
            'initializing_email': "📧 Initializing Email Alert System...",
            'loading_data': "📊 Loading and preprocessing data...",
            'running_analytics': "🔍 Running analytics...",
            'initializing_alerts': "🚨 Initializing Alert Engine...",
            'generating_alerts': "🔔 Generating initial alerts...",
            'no_failure_column': "Warning: 'failure' column not found. Skipping model training.",
            'no_failure_prob': "Warning: Could not run alert engine - missing 'failure_prob' column",
            'alerts_generated': "Total alerts generated:",
            'email_system_configured': "Email system: Configured",
            'manual_email_control': "💡 IMPORTANT: Emails will NOT be sent automatically!",
            'use_dashboard_buttons': "Use the dashboard buttons to send emails manually.",
            'high_failure_alert': "High Failure Probability Alert",
            'critical_failure_prob': "Machine {} has critical failure probability of {:.1%}",
            'low_health_alert': "Low Health Score Alert",
            'critically_low_health': "Machine {} health is critically low at {:.1f}",
            'anomaly_detected': "Anomaly Detected",
            'unusual_behavior': "Unusual behavior detected on machine {}",
            'high_tool_wear': "High Tool Wear Alert",
            'tool_wear_high': "Machine {} tool wear is high at {} minutes",
            'status': "Status",
            'tool_wear_min': "Tool Wear",
            'vibration': "Vibration",
            'temp_diff': "Temperature Diff",
            'power_usage': "Power Usage",
            'alert_message': "Alert Message",
            'recommended_actions': "Recommended Actions",
            'alert_id': "Alert ID",
            'time': "Time",
            'never': "Never",
            'today_alerts': "Today's Alerts",
            'critical_alerts_today': "Critical Alerts Today",
            'avg_health_score': "Avg Health Score",
            'machines_need_attention': "Machines Need Attention",
            'total_alerts': "Total Alerts",
            'immediate': "Immediate",
            'scheduled': "Scheduled",
            'monitor': "Monitor",
            'excellent': "Excellent",
            'good': "Good",
            'fair': "Fair",
            'poor': "Poor",
            'email_sent': "✅ Email alert sent: {} - {}",
            'network_unreachable': "⚠️ Email not sent: Network unreachable.",
            'auth_failed': "❌ Email not sent: Authentication failed.",
            'failed_send': "❌ Failed to send email alert: {}",
            'alert_cooldown': "Alert on cooldown for {} ({:.1f} minutes since last)",
            'sent_critical_summary': "✅ Sent summary of {} critical alerts!",
            'failed_critical_summary': "❌ Failed to send critical alerts summary",
            'test_alert_title': "Test Alert from BRUSS Dashboard",
            'test_alert_message': "This is a test email sent to {}",
            'daily_report_title': "Daily Maintenance Report - {}",
            'daily_report_message': "Daily summary of machine health and alerts for {}",
            'critical_summary_title': "Critical Alerts Summary: {} issues",
            'critical_summary_message': "Found {} critical/high alerts requiring attention.",
            # Shift report
            'shift_report_title': "📄 Shift Handover Report",
            'shift_report_subtitle': "Auto-generate PDF at shift end (6am / 2pm / 10pm)",
            'generate_shift_report': "📥 Generate Shift Report Now",
            'send_shift_report_email': "📧 Generate & Email Report",
            'shift_select_label': "Select Shift:",
            'shift_report_generated': "✅ Shift report generated!",
            'shift_report_emailed': "✅ Shift report generated and emailed!",
            'shift_report_failed': "❌ Failed to generate shift report.",
            'download_report': "⬇️ Download Last Report",
        },
        'de': {
            'dashboard_title': "🔧 BRUSS Predictive Maintenance Dashboard",
            'dashboard_subtitle': "Echtzeit-Überwachung, Predictive Analytics und E-Mail-Benachrichtigungen",
            'language_label': "🌐 Sprache / Language",
            'total_machines': "Maschinen gesamt",
            'critical_alerts': "Kritische Warnungen",
            'email_status': "E-Mail-Status",
            'email_controls': "📧 E-Mail-Benachrichtigungen",
            'test_email_recipient': "Test-E-Mail-Empfänger:",
            'send_test_email': "Test-E-Mail senden",
            'quick_actions': "Schnellaktionen:",
            'send_daily_report': "📋 Tagesbericht senden",
            'send_critical_alerts': "⚠️ Kritische Warnungen senden",
            'recent_alerts': "🚨 Aktuelle Warnungen",
            'no_recent_alerts': "Keine aktuellen Warnungen",
            'select_machines': "🏭 Maschinen auswählen",
            'select_time_range': "📈 Zeitraum auswählen",
            'overview': "📊 Übersicht",
            'sensor_analytics': "📈 Sensoranalyse",
            'predictive_insights': "🔍 Predictive Insights",
            'maintenance_schedule': "📋 Wartungsplan",
            'email_history': "📧 E-Mail-Verlauf",
            'visual_diagnostics': "🔬 Visuelle Diagnose",
            'shift_report': "📄 Schichtübergabebericht",
            'health_distribution': "Health-Score-Verteilung",
            'risk_distribution': "Risikostufen-Verteilung",
            'temperature_trends': "Temperaturverlauf",
            'power_vibration': "Leistung & Vibration",
            'tool_wear': "Werkzeugverschleiß",
            'vibration_analysis': "3D-Vibrationsanalyse",
            'failure_probability': "Ausfallwahrscheinlichkeit über Zeit",
            'rul_estimation': "Top 20 Maschinen nach geschätzter RUL",
            'feature_importance': "Feature-Importanz für Ausfallvorhersage",
            'maintenance_recommendations': "🛠️ Wartungsempfehlungen",
            'machine_id': "Maschinen-ID",
            'health_score': "Health-Score",
            'risk_level': "Risikostufe",
            'estimated_rul': "Geschätzte RUL (Stunden)",
            'maintenance_urgency': "Wartungsdringlichkeit",
            'recommended_action': "Empfohlene Aktion",
            'email_alert_history': "📧 E-Mail-Benachrichtigungsverlauf",
            'email_stats': "📧 E-Mail-Statistiken (letzte 24h)",
            'total_sent': "Gesendet:",
            'critical': "Kritisch",
            'last_alert': "Letzte Benachrichtigung:",
            'timestamp': "Zeitstempel",
            'severity': "Schweregrad",
            'subject': "Betreff",
            'recipients': "Empfänger",
            'select_machine_type': "Maschinentyp auswählen:",
            'select_machine_id': "Maschinen-ID auswählen:",
            'cnc_machine': "CNC-Maschine",
            'rep_machine': "Roboter End-Effektor",
            'part_status': "Bauteil-Status",
            'normal': "Normal",
            'warning': "Warnung",
            'machine_schematic': "Maschinen-Schematic",
            'part_alerts': "Bauteil-Warnungen",
            'machine_details': "Maschinendetails",
            'current_health': "Aktueller Health-Score:",
            'failure_prob': "Ausfallwahrscheinlichkeit:",
            'machine_type': "Maschinentyp:",
            'last_update': "Letzte Aktualisierung:",
            'no_data_for_machine': "Keine Daten für ausgewählte Maschine verfügbar",
            'initializing_email': "📧 Initialisiere E-Mail-Benachrichtigungssystem...",
            'loading_data': "📊 Lade und verarbeite Daten...",
            'running_analytics': "🔍 Führe Analysen durch...",
            'initializing_alerts': "🚨 Initialisiere Warnsystem...",
            'generating_alerts': "🔔 Erzeuge initiale Warnungen...",
            'no_failure_column': "Warnung: 'failure' Spalte nicht gefunden.",
            'no_failure_prob': "Warnung: Warnsystem konnte nicht ausgeführt werden.",
            'alerts_generated': "Warnungen generiert:",
            'email_system_configured': "E-Mail-System: Konfiguriert",
            'manual_email_control': "💡 WICHTIG: E-Mails werden NICHT automatisch gesendet!",
            'use_dashboard_buttons': "Benutze die Dashboard-Buttons, um E-Mails manuell zu senden.",
            'high_failure_alert': "Hohe Ausfallwahrscheinlichkeit",
            'critical_failure_prob': "Maschine {} hat kritische Ausfallwahrscheinlichkeit von {:.1%}",
            'low_health_alert': "Niedriger Health-Score",
            'critically_low_health': "Health-Score von Maschine {} ist kritisch niedrig bei {:.1f}",
            'anomaly_detected': "Anomalie erkannt",
            'unusual_behavior': "Ungewöhnliches Verhalten bei Maschine {} erkannt",
            'high_tool_wear': "Hoher Werkzeugverschleiß",
            'tool_wear_high': "Werkzeugverschleiß von Maschine {} ist hoch bei {} Minuten",
            'status': "Status",
            'tool_wear_min': "Werkzeugverschleiß",
            'vibration': "Vibration",
            'temp_diff': "Temperaturdifferenz",
            'power_usage': "Leistungsaufnahme",
            'alert_message': "Benachrichtigungsnachricht",
            'recommended_actions': "Empfohlene Aktionen",
            'alert_id': "Benachrichtigungs-ID",
            'time': "Zeit",
            'never': "Nie",
            'today_alerts': "Heutige Benachrichtigungen",
            'critical_alerts_today': "Kritische Benachrichtigungen heute",
            'avg_health_score': "Durchschn. Health-Score",
            'machines_need_attention': "Maschinen benötigen Aufmerksamkeit",
            'total_alerts': "Benachrichtigungen gesamt",
            'immediate': "Sofort",
            'scheduled': "Geplant",
            'monitor': "Überwachen",
            'excellent': "Ausgezeichnet",
            'good': "Gut",
            'fair': "Akzeptabel",
            'poor': "Schlecht",
            'email_sent': "✅ E-Mail-Benachrichtigung gesendet: {} - {}",
            'network_unreachable': "⚠️ E-Mail nicht gesendet: Netzwerk nicht erreichbar.",
            'auth_failed': "❌ E-Mail nicht gesendet: Authentifizierung fehlgeschlagen.",
            'failed_send': "❌ Fehler beim Senden der E-Mail-Benachrichtigung: {}",
            'alert_cooldown': "Benachrichtigung in Abkühlphase für {} ({:.1f} Minuten seit letzter)",
            'sent_critical_summary': "✅ Zusammenfassung von {} kritischen Benachrichtigungen gesendet!",
            'failed_critical_summary': "❌ Fehler beim Senden der kritischen Benachrichtigungen",
            'test_alert_title': "Testbenachrichtigung von BRUSS Dashboard",
            'test_alert_message': "Dies ist eine Test-E-Mail gesendet an {}",
            'daily_report_title': "Tagesbericht Wartung - {}",
            'daily_report_message': "Tägliche Zusammenfassung des Maschinenzustands und Benachrichtigungen für {}",
            'critical_summary_title': "Zusammenfassung kritischer Benachrichtigungen: {} Probleme",
            'critical_summary_message': "{} kritische/hohe Benachrichtigungen erfordern Aufmerksamkeit.",
            # Shift report
            'shift_report_title': "📄 Schichtübergabebericht",
            'shift_report_subtitle': "PDF automatisch am Schichtende (6:00 / 14:00 / 22:00 Uhr)",
            'generate_shift_report': "📥 Schichtbericht jetzt erstellen",
            'send_shift_report_email': "📧 Erstellen & per E-Mail senden",
            'shift_select_label': "Schicht auswählen:",
            'shift_report_generated': "✅ Schichtbericht erstellt!",
            'shift_report_emailed': "✅ Schichtbericht erstellt und per E-Mail gesendet!",
            'shift_report_failed': "❌ Fehler beim Erstellen des Schichtberichts.",
            'download_report': "⬇️ Letzten Bericht herunterladen",
        }
    }

    def __init__(self, default_lang: str = 'en'):
        self.current_lang = default_lang

    def get_text(self, key: str, *format_args) -> str:
        text = self.TRANSLATIONS.get(self.current_lang, self.TRANSLATIONS['en']).get(key, key)
        if format_args:
            try:
                return text.format(*format_args)
            except Exception:
                return text
        return text

    def set_language(self, lang: str):
        if lang in self.TRANSLATIONS:
            self.current_lang = lang

    def get_language_options(self) -> list:
        return [
            {'label': 'English 🇬🇧', 'value': 'en'},
            {'label': 'Deutsch 🇩🇪', 'value': 'de'},
        ]
